### ISSUE TITLE
#40 - Sub issue - Toolbar feature task list/tracker

### ISSUE THREAD

**Issue by ramity** [ramity/CTTP-Lab-Cert#49]
# Required
- [x] User can open toolbar
- [x] Toolbar generates formline (height 25px to allow 8 lines by standard height) that includes:
  - [x] label = from selected item(s)
  - [x] description = manually entered :(
  - [x] tag = text is default (select box with all tag options) - considering on changing text to input
  - [x] input_placeholder = manually entered :(
  - [x] name = auto generated (lowercase label, spaces to _, remove :s) - editable in toolbar
  - [ ] sql = auto generated after name and required are available
  - [x] required = default is 1
  - [x] xl = from selected item(s) - ability to select multiple cells for single
  - [x] value = can be selected via excel sheet function of some sort and/or edited that way
- [x] User can select items via spreadsheet
- [ ] toolbar implements a reorder function
- [ ] user can pick up formline and drag and drop the formline to reorder the form.
# Optional
- [ ] future ability to edit created calibrations?
